spring:
  application:
    name: auth-server
  redis:
    database: 14
    host: 10.138.25.20
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
server:
  port: 6001
