spring:
  application:
    name: auth-server
  redis:
    database: 14
    host: 10.138.25.20
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
server:
  port: 6101


#security:
#  oauth2:
#    client:
#      client-id: user-client
#      client-secret: user-secret-8888
#      user-authorization-uri: http://localhost:6001/oauth/authorize
#      access-token-uri: http://localhost:6001/oauth/token
#    resource:
#      id: user-client
#      user-info-uri: user-info
#    authorization:
#      check-token-access: http://localhost:6001/oauth/check_token
#
#

security:
  oauth2:
    client:
      client-id: user-client
      client-secret: user-secret-8888
      user-authorization-uri: http://localhost:6001/oauth/authorize
      access-token-uri: http://localhost:6001/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:6001/oauth/token_key
        key-value: dev