server:
  port: 6101

spring:
  profiles:
    active: prod

#security:
#  oauth2:
#    client:
#      client-id: user-client
#      client-secret: user-secret-8888
#      user-authorization-uri: http://localhost:6001/oauth/authorize
#      access-token-uri: http://localhost:6001/oauth/token
#    resource:
#      id: user-client
#      user-info-uri: user-info
#    authorization:
#      check-token-access: http://localhost:6001/oauth/check_token
#
#

security:
  oauth2:
    client:
      client-id: user-client
      client-secret: user-secret-8888
      user-authorization-uri: http://localhost:6001/oauth/authorize
      access-token-uri: http://localhost:6001/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:6001/oauth/token_key

        key-value: dev