server:
  port: 9527

spring:
  profiles:
    active: prod
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allow-credentials: true
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
      routes:
        - id: auth_route
          uri: lb://airport-auth
          predicates:
            - Path=/auth/**
        - id: health_route
          uri: lb://airport-health
          predicates:
            - Path=/health/**





