server:
  port: 9527


spring:
  application:
    name: airport-gateway
  cloud:
    gateway:
      routes:
        -id: seckill-provider-route
        uri: lb://auth-server
        predicates:
         -Path=/auth/**